blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(("users.urls",'users'),namespace='users')),
    path('', include(('home.urls','home'),namespace='home')),
]

import logging

logger=logging.getLogger('django')
logger.debug("这是debug")
logger.info('这是info')
logger.error("这是error")

#以下代码为设置图片访问路由规则
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/home/urls.py
from django.urls import path
from home.views import IndexView


urlpatterns=[
    path('', IndexView.as_view(),name='index'),
]

blog/users/urls.py
from django.urls import path
from users.views import RegisterView,ImageCodeView,SmsCodeView,LoginView,LogoutView,ForgetPasswordView \
    ,UserCenterView,WriteBlogView


urlpatterns=[
    path("register/",RegisterView.as_view(),name='register'),
    path('imagecode/',ImageCodeView.as_view()),
    path("smscode/",SmsCodeView.as_view(),name='smscode'),
    path('login/', LoginView.as_view(),name='login'),
    path("logout/",LogoutView.as_view(),name='logout'),
    path("forgetpassword/",ForgetPasswordView.as_view(),name='forgetpassword'),
    path("center/", UserCenterView.as_view(),name='center'),
    path('writeblog/', WriteBlogView.as_view(),name='writeblog'),
]

blog/templates/center.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title> 用户信息 </title>
    {% load staticfiles %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">个人博客</a>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown" v-if="is_login">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">{{ username }}</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                    <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                    <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                    <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                </div>
            </li>
            <!-- 如果用户未登录，则显示登录按钮 -->
            <li class="nav-item" v-else>
                <a class="nav-link" href="login.html">登录</a>
            </li>

        </ul>
    </div>
</nav>

<!--content-->
<div class="container" style="margin-bottom: 20px">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <!-- username -->
                <div class="form-group col-md-4">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ username }}" >
                </div>
                <!--<br><h5 class="col-md-4">暂无头像</h5><br>-->

                <br> <div class="col-md-4">头像</div>
                    {% if avatar %}
                        <img src="{{ avater }}" style="max-width: 20%;" class="col-md-4"><br>
                    {% else %}
                        <img src="{% static 'img/mei.png' %}" style="max-width: 20%;" class="col-md-4"><br>
                    {% endif %}
                    <!-- avatar -->
                    <div class="form-group col-md-4">
                        <label for="avatar">上传头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <!-- phone -->
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" disabled="disabled" id="phone" name="phone" value="{{ mobile }}">
                    </div>
                    <!-- desc -->
                    <div class="form-group col-md-4">
                        <label for="desc">简介</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="desc" name="desc" rows="12" >{{ user_desc }}</textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary" style="margin-left: 12px" >修改</button>
                </form>
            </div>
        </div>
    </div>


<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/center.js' %}"></script>
</body>

</html>

blog/templates/index.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>首页</title>
    {% load staticfiles %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--导入css-->
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">个人博客</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse">
            <div>
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link mr-2" href="#">Python</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">Java</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">C</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mr-2" href="#">C++</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
            <ul class="nav navbar-nav">
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown" v-if="is_login">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" @click="show_menu_click">[[username]]</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display: block" v-show="show_menu">
                        <a class="dropdown-item" href="{% url 'users:writeblog' %}">写文章</a>
                        <a class="dropdown-item" href='{% url 'users:center' %}'>个人信息</a>
                        <a class="dropdown-item" href='{% url 'users:logout' %}'>退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示登录按钮 -->
                <li class="nav-item" v-else>
                    <a class="nav-link" href="#">登录</a>
                </li>
            </ul>
    </div>
</nav>

<!-- content -->
<div class="container">
    <!-- 列表循环 -->
    <div class="row mt-2">
            <!-- 文章内容 -->
            <!-- 标题图 -->
            <div class="col-3">
                <img src="{% static 'img/1.jpg' %}" alt="avatar" style="max-width:100%; border-radius: 20px">
            </div>
            <div class="col">
                <!-- 栏目 -->
                <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
                <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
                <!-- 标题 -->
                <h4>
                    <b><a href="./detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 查看、评论、时间 -->
                    <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                    <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
                </p>
            </div>
            <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="{% static 'img/1.jpg' %}" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="{% static 'img/1.jpg' %}" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="{% static 'img/1.jpg' %}" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>

    <div class="row mt-2">
        <!-- 文章内容 -->
        <!-- 标题图 -->
        <div class="col-3">
            <img src="{% static 'img/1.jpg' %}" alt="avatar" style="max-width:100%; border-radius: 20px">
        </div>
        <div class="col">
            <!-- 栏目 -->
            <a  role="button" href="#" class="btn btn-sm mb-2 btn-warning">Python</a>
            <!-- 标签 -->
            <span>
                        <a href="#" class="badge badge-secondary">Django</a>
                </span>
            <!-- 标题 -->
            <h4>
                <b><a href="detail.html" style="color: black;">如何更好的学习Django呢？</a></b>
            </h4>
            <!-- 摘要 -->
            <div>
                <p style="color: gray;">
                    Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django。Django是一个开放源代码的Web应用框架，由Python写成。
                </p>
            </div>
            <!-- 注脚 -->
            <p>
                <!-- 转发、评论、时间 -->
                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>590&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>11&nbsp;&nbsp;&nbsp;</span>
                <span><i class="fas fa-clock" style="color: pink;"></i>2019-10-22</span>
            </p>
        </div>
        <hr style="width: 100%;"/>
    </div>
    <!-- 页码导航 -->
    <div class="pagenation" style="text-align: center">
        <div id="pagination" class="page"></div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>

<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
{#<script type="text/javascript" src="{% static 'js/register.js' %}"></script>#}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: 15,
            totalPage: 30,
            callback:function (current) {

                location.href = '/';
            }
        })
    });
</script>
</body>
</html>

blog/templates/login.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>登录</title>
    {% load staticfiles %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>

<body>
<div id="app">

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">个人博客</a>
        </div>
    </div>
    <div class="navbar-collapse">
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    <div class="form-group">
                        <label for="id_login">账号: </label>
                        <input type="text" name="mobile" placeholder="请输入手机号" autofocus="autofocus" required id="id_login" class="form-control" v-model="mobile" @blur="check_mobile"/>
                        <small class="form-text text-muted ml-1">还没有账号？<a href="{% url 'users:register' %}" style="color: cornflowerblue; ">注册新账号</a>
                        </small>
                    </div>
                    <div class="form-group mb-1">
                        <label for="id_password">密码:</label>
                        <input type="password" name="password" placeholder="请输入密码" required id="id_password" class="form-control" v-model="password" @blur="check_password"/>
                        <small class="form-text text-muted ml-1"><a class="secondaryAction layui-text" href="{% url 'users:forgetpassword' %}">忘记密码?</a>
                        </small>
                    </div>
                    <div class="custom-control custom-checkbox mb-2">
                        <input type="checkbox" name="remember" id="id_remember" checked class="custom-control-input" v-model="remembered"/>
                        <label for="id_remember" class="custom-control-label">保持登录</label>
                    </div>
                    <button class="primaryAction btn btn-primary" type="submit" id="submit_login" @click="on_submit">登录</button>
                </form>
            </div>
        </div>
    </div>
</div>

    
<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>

</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</body>

</html>

blog/templates/register.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    {% load staticfiles %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>
<body>
<div id="app">


<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="{% url 'home:index' %}">个人博客</a>
        </div>
    </div>
    <!--登录/个人中心-->
    <div class="navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">登录</a>
            </li>
        </ul>
    </div>
</nav>
<!--content-->
<div class="container" style="height: 600px;margin-top: 20px">
    <div class="row" >
        <div class="col-12">
            <div class="col-6">
                <form class="login" id="login_form" method="POST">
                    <!--手机号-->
                    {%csrf_token%}
                    <div class="form-group">
                        <label >手机号: </label>
                        <div class="col-lg-6">
                            <input type="text" name="mobile" placeholder="请输入手机号" autofocus="autofocus" required
                                   id="id_login" class="form-control" v-model="mobile" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="mobile_error" >[[mobile_error_message]]</small>
                    </div>
                    <!--密码-->
                    <div class="form-group">
                        <label >密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password" placeholder="请输入密码" required  class="form-control" v-model="password" @blur="check_password" />
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password_error" >[[password_error_message]]</small>
                    </div>
                    <!--确认密码-->
                    <div class="form-group">
                        <label >确认密码:</label>
                        <div class="col-lg-6">
                            <input type="password" name="password2" placeholder="请输入确认密码" required  class="form-control" v-model="password2" @blur="check_password2"/>
                        </div>
                        <small class="form-text text-muted ml-1" v-show="password2_error" >[[password2_error_message]]</small>
                    </div>
                   <!--图片验证码-->
                    <div class="form-group">
                        <label >图片验证码:</label>
                        <div class="row" style="margin-right:5px;margin-left:0px">
                            <div class="col-lg-6">
                                <input type="text" name="imgage_code" placeholder="请输入图片验证码" required  class="form-control" v-model="image_code" @blur="check_image_code"/>
                            </div>
                            <img :src="image_code_url" @click="generate_image_code" alt="" style="width: 110px;height: 40px;">
                            <small class="form-text text-muted ml-1" v-show="image_code_error" >[[image_code_error_message]]</small>
                        </div>
                    </div>
                   <!--短信验证码-->
                    <div class="form-group">
                        <label >短信验证码:</label>
                        <div class="row" style="margin-right:5px;margin-left:0px">
                            <div class="col-lg-6">
                                <input type="text" name="sms_code" placeholder="请输入短信验证码" required  class="form-control" v-model="sms_code" @blur="check_sms_code"/>
                            </div>
                            <span class="primaryAction btn btn-primary" @click="send_sms_code">[[sms_code_message]]</span>
                            <small class="form-text text-muted ml-1" v-show="sms_code_error" >[[sms_code_error_message]]</small>
                        </div>
                        </div>
                    <button class="primaryAction btn btn-primary" type="submit" id="submit_login" @click="on_submit">注册</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright @ qiruihua</h5>
    </div>
</footer>
</div>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</body>
</html>